spring:
  application:
    name: tlias-web-management
  #mysql????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  helper-dialect: mysql
  #spring事务管理日志
logging:
    level:
      org.springframework.jdbc.support.JdbcTransactionManager: debug
#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-01-chd
    region: cn-beijing